\set ON_ERROR_STOP on

DO $setup$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'teslamate_cost_mcp') THEN
    CREATE ROLE teslamate_cost_mcp LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
  END IF;
END
$setup$;

SELECT format(
  'ALTER ROLE teslamate_cost_mcp PASSWORD %L',
  rtrim(pg_read_file('/tmp/teslamate_cost_mcp_db_password'), E' \t\n\r')
) \gexec

ALTER ROLE teslamate_cost_mcp SET statement_timeout = '5s';
REVOKE ALL ON DATABASE teslamate FROM teslamate_cost_mcp;
GRANT CONNECT ON DATABASE teslamate TO teslamate_cost_mcp;

CREATE SCHEMA IF NOT EXISTS teslamate_cost_mcp AUTHORIZATION teslamate;
ALTER SCHEMA teslamate_cost_mcp OWNER TO teslamate;

CREATE TABLE IF NOT EXISTS teslamate_cost_mcp.cost_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL UNIQUE,
  actor text NOT NULL CHECK (actor IN ('huunter', 'guoguo')),
  charging_process_id integer NOT NULL,
  previous_cost numeric(6,2),
  new_cost numeric(6,2),
  source_kind text NOT NULL CHECK (source_kind IN ('text', 'screenshot')),
  source_summary text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE teslamate_cost_mcp.cost_audit OWNER TO teslamate;

CREATE OR REPLACE VIEW teslamate_cost_mcp.charging_sessions AS
SELECT cp.id,
       cp.car_id,
       cp.start_date,
       cp.end_date,
       cp.duration_min,
       cp.charge_energy_added,
       cp.charge_energy_used,
       cp.cost,
       cp.start_battery_level,
       cp.end_battery_level,
       COALESCE(
         g.name,
         NULLIF(a.name, ''),
         NULLIF(
           concat_ws(
             ', ',
             NULLIF(concat_ws(' ', a.road, a.house_number), ''),
             a.city
           ),
           ''
         )
       ) AS address
FROM public.charging_processes cp
LEFT JOIN public.addresses a ON a.id = cp.address_id
LEFT JOIN public.geofences g ON g.id = cp.geofence_id;
ALTER VIEW teslamate_cost_mcp.charging_sessions OWNER TO teslamate;

CREATE OR REPLACE VIEW teslamate_cost_mcp.cost_history AS
SELECT ca.id AS audit_id,
       ca.request_id,
       ca.actor,
       ca.charging_process_id,
       ca.previous_cost,
       ca.new_cost,
       ca.source_kind,
       ca.source_summary,
       ca.created_at
FROM teslamate_cost_mcp.cost_audit ca;
ALTER VIEW teslamate_cost_mcp.cost_history OWNER TO teslamate;

CREATE OR REPLACE FUNCTION teslamate_cost_mcp.apply_cost_change(
  p_request_id uuid,
  p_actor text,
  p_session_id integer,
  p_expected_cost numeric,
  p_new_cost numeric,
  p_source_kind text,
  p_source_summary text
)
RETURNS TABLE (
  audit_id bigint,
  session_id integer,
  previous_cost numeric,
  new_cost numeric,
  applied_at timestamptz,
  idempotent boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, teslamate_cost_mcp
AS $function$
DECLARE
  existing teslamate_cost_mcp.cost_audit%ROWTYPE;
  current_row public.charging_processes%ROWTYPE;
  inserted teslamate_cost_mcp.cost_audit%ROWTYPE;
BEGIN
  IF p_actor NOT IN ('huunter', 'guoguo') THEN
    RAISE EXCEPTION 'unauthorized actor';
  END IF;
  IF p_source_kind NOT IN ('text', 'screenshot') THEN
    RAISE EXCEPTION 'invalid source kind';
  END IF;
  IF p_new_cost IS NOT NULL AND (p_new_cost < 0 OR p_new_cost > 9999.99) THEN
    RAISE EXCEPTION 'cost must be between 0.00 and 9999.99';
  END IF;
  IF length(COALESCE(p_source_summary, '')) > 500 THEN
    RAISE EXCEPTION 'source summary is too long';
  END IF;

  SELECT * INTO existing
  FROM teslamate_cost_mcp.cost_audit
  WHERE request_id = p_request_id;

  IF FOUND THEN
    IF existing.actor IS DISTINCT FROM p_actor
       OR existing.charging_process_id IS DISTINCT FROM p_session_id
       OR existing.new_cost IS DISTINCT FROM p_new_cost THEN
      RAISE EXCEPTION 'request id was already used for a different change';
    END IF;
    RETURN QUERY SELECT existing.id,
                        existing.charging_process_id,
                        existing.previous_cost,
                        existing.new_cost,
                        existing.created_at,
                        true;
    RETURN;
  END IF;

  SELECT * INTO current_row
  FROM public.charging_processes
  WHERE id = p_session_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'unknown charging session: %', p_session_id;
  END IF;
  IF current_row.end_date IS NULL THEN
    RAISE EXCEPTION 'charging session is not complete';
  END IF;
  IF current_row.cost IS DISTINCT FROM p_expected_cost THEN
    RAISE EXCEPTION 'cost conflict: expected %, current %', p_expected_cost, current_row.cost;
  END IF;

  UPDATE public.charging_processes
  SET cost = p_new_cost
  WHERE id = p_session_id;

  INSERT INTO teslamate_cost_mcp.cost_audit (
    request_id,
    actor,
    charging_process_id,
    previous_cost,
    new_cost,
    source_kind,
    source_summary
  )
  VALUES (
    p_request_id,
    p_actor,
    p_session_id,
    current_row.cost,
    p_new_cost,
    p_source_kind,
    COALESCE(p_source_summary, '')
  )
  RETURNING * INTO inserted;

  RETURN QUERY SELECT inserted.id,
                      inserted.charging_process_id,
                      inserted.previous_cost,
                      inserted.new_cost,
                      inserted.created_at,
                      false;
END
$function$;
ALTER FUNCTION teslamate_cost_mcp.apply_cost_change(
  uuid, text, integer, numeric, numeric, text, text
) OWNER TO teslamate;

REVOKE ALL ON SCHEMA public FROM teslamate_cost_mcp;
REVOKE ALL ON SCHEMA teslamate_cost_mcp FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA teslamate_cost_mcp FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA teslamate_cost_mcp FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA teslamate_cost_mcp FROM teslamate_cost_mcp;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA teslamate_cost_mcp FROM teslamate_cost_mcp;

GRANT USAGE ON SCHEMA teslamate_cost_mcp TO teslamate_cost_mcp;
GRANT SELECT ON teslamate_cost_mcp.charging_sessions TO teslamate_cost_mcp;
GRANT SELECT ON teslamate_cost_mcp.cost_history TO teslamate_cost_mcp;
GRANT EXECUTE ON FUNCTION teslamate_cost_mcp.apply_cost_change(
  uuid, text, integer, numeric, numeric, text, text
) TO teslamate_cost_mcp;
