\set ON_ERROR_STOP on

DO $setup$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'teslamate_cost_mcp') THEN
    CREATE ROLE teslamate_cost_mcp LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
  END IF;
END
$setup$;

SELECT format(
  'ALTER ROLE teslamate_cost_mcp PASSWORD %L',
  rtrim(pg_read_file('/tmp/teslamate_cost_mcp_db_password'), E' \t\n\r')
) \gexec

ALTER ROLE teslamate_cost_mcp SET statement_timeout = '5s';
REVOKE ALL ON DATABASE teslamate FROM teslamate_cost_mcp;
GRANT CONNECT ON DATABASE teslamate TO teslamate_cost_mcp;

CREATE SCHEMA IF NOT EXISTS teslamate_cost_mcp AUTHORIZATION teslamate;
ALTER SCHEMA teslamate_cost_mcp OWNER TO teslamate;

CREATE TABLE IF NOT EXISTS teslamate_cost_mcp.cost_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL UNIQUE,
  actor text NOT NULL CHECK (actor IN ('huunter', 'guoguo')),
  charging_process_id integer NOT NULL,
  previous_cost numeric(6,2),
  new_cost numeric(6,2),
  source_kind text NOT NULL CHECK (source_kind IN ('text', 'screenshot')),
  source_summary text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE teslamate_cost_mcp.cost_audit OWNER TO teslamate;

CREATE TABLE IF NOT EXISTS teslamate_cost_mcp.road_journeys (
  id uuid PRIMARY KEY,
  car_id integer NOT NULL,
  drive_signature text NOT NULL UNIQUE,
  start_date timestamp without time zone NOT NULL,
  end_date timestamp without time zone NOT NULL,
  start_label text NOT NULL DEFAULT '',
  end_label text NOT NULL DEFAULT '',
  match_confidence numeric(4,3),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (end_date >= start_date),
  CHECK (match_confidence IS NULL OR match_confidence BETWEEN 0 AND 1)
);
ALTER TABLE teslamate_cost_mcp.road_journeys OWNER TO teslamate;

CREATE TABLE IF NOT EXISTS teslamate_cost_mcp.road_journey_drives (
  journey_id uuid NOT NULL REFERENCES teslamate_cost_mcp.road_journeys(id) ON DELETE CASCADE,
  drive_id integer NOT NULL REFERENCES public.drives(id),
  sequence_no smallint NOT NULL CHECK (sequence_no BETWEEN 1 AND 20),
  PRIMARY KEY (journey_id, drive_id),
  UNIQUE (journey_id, sequence_no)
);
ALTER TABLE teslamate_cost_mcp.road_journey_drives OWNER TO teslamate;

CREATE TABLE IF NOT EXISTS teslamate_cost_mcp.toll_expenses (
  id uuid PRIMARY KEY,
  actor text NOT NULL CHECK (actor IN ('huunter', 'guoguo')),
  journey_id uuid REFERENCES teslamate_cost_mcp.road_journeys(id),
  revision integer NOT NULL DEFAULT 1 CHECK (revision > 0),
  amount numeric(6,2) NOT NULL CHECK (amount BETWEEN 0 AND 9999.99),
  occurred_at timestamp without time zone NOT NULL,
  entry_name text NOT NULL DEFAULT '',
  exit_name text NOT NULL DEFAULT '',
  provider text NOT NULL CHECK (provider IN ('manual', 'etc', 'wechat', 'alipay', 'other')),
  external_ref text NOT NULL DEFAULT '',
  receipt_fingerprint text NOT NULL,
  source_kind text NOT NULL CHECK (source_kind IN ('text', 'screenshot')),
  source_summary text NOT NULL DEFAULT '',
  status text NOT NULL CHECK (status IN ('matched', 'pending_match', 'void')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE teslamate_cost_mcp.toll_expenses OWNER TO teslamate;

CREATE UNIQUE INDEX IF NOT EXISTS toll_expenses_external_ref_unique
ON teslamate_cost_mcp.toll_expenses (provider, external_ref)
WHERE external_ref <> '' AND status <> 'void';

CREATE INDEX IF NOT EXISTS toll_expenses_fingerprint_idx
ON teslamate_cost_mcp.toll_expenses (receipt_fingerprint, occurred_at DESC);

CREATE TABLE IF NOT EXISTS teslamate_cost_mcp.toll_expense_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL UNIQUE,
  expense_id uuid NOT NULL REFERENCES teslamate_cost_mcp.toll_expenses(id),
  actor text NOT NULL CHECK (actor IN ('huunter', 'guoguo')),
  operation text NOT NULL CHECK (operation IN ('upsert', 'void')),
  previous_state jsonb,
  new_state jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE teslamate_cost_mcp.toll_expense_audit OWNER TO teslamate;

CREATE OR REPLACE VIEW teslamate_cost_mcp.charging_sessions AS
SELECT cp.id,
       cp.car_id,
       cp.start_date,
       cp.end_date,
       cp.duration_min,
       cp.charge_energy_added,
       cp.charge_energy_used,
       cp.cost,
       cp.start_battery_level,
       cp.end_battery_level,
       COALESCE(
         g.name,
         NULLIF(a.name, ''),
         NULLIF(
           concat_ws(
             ', ',
             NULLIF(concat_ws(' ', a.road, a.house_number), ''),
             a.city
           ),
           ''
         )
       ) AS address,
       g.name AS geofence,
       a.city AS city
FROM public.charging_processes cp
LEFT JOIN public.addresses a ON a.id = cp.address_id
LEFT JOIN public.geofences g ON g.id = cp.geofence_id;
ALTER VIEW teslamate_cost_mcp.charging_sessions OWNER TO teslamate;

CREATE OR REPLACE VIEW teslamate_cost_mcp.cost_history AS
SELECT ca.id AS audit_id,
       ca.request_id,
       ca.actor,
       ca.charging_process_id,
       ca.previous_cost,
       ca.new_cost,
       ca.source_kind,
       ca.source_summary,
       ca.created_at
FROM teslamate_cost_mcp.cost_audit ca;
ALTER VIEW teslamate_cost_mcp.cost_history OWNER TO teslamate;

CREATE OR REPLACE VIEW teslamate_cost_mcp.toll_candidate_drives AS
SELECT d.id,
       d.car_id,
       d.start_date,
       d.end_date,
       d.distance,
       d.duration_min,
       sp.latitude AS start_latitude,
       sp.longitude AS start_longitude,
       ep.latitude AS end_latitude,
       ep.longitude AS end_longitude,
       COALESCE(
         sg.name,
         NULLIF(sa.name, ''),
         NULLIF(concat_ws(', ', NULLIF(concat_ws(' ', sa.road, sa.house_number), ''), sa.city), '')
       ) AS start_address,
       COALESCE(
         eg.name,
         NULLIF(ea.name, ''),
         NULLIF(concat_ws(', ', NULLIF(concat_ws(' ', ea.road, ea.house_number), ''), ea.city), '')
       ) AS end_address,
       sg.name AS start_geofence,
       sa.city AS start_city,
       eg.name AS end_geofence,
       ea.city AS end_city
FROM public.drives d
LEFT JOIN public.positions sp ON sp.id = d.start_position_id
LEFT JOIN public.positions ep ON ep.id = d.end_position_id
LEFT JOIN public.addresses sa ON sa.id = d.start_address_id
LEFT JOIN public.addresses ea ON ea.id = d.end_address_id
LEFT JOIN public.geofences sg ON sg.id = d.start_geofence_id
LEFT JOIN public.geofences eg ON eg.id = d.end_geofence_id;
ALTER VIEW teslamate_cost_mcp.toll_candidate_drives OWNER TO teslamate;

CREATE OR REPLACE VIEW teslamate_cost_mcp.toll_expense_current AS
SELECT te.id AS expense_id,
       te.actor,
       te.journey_id,
       te.revision,
       te.amount,
       te.occurred_at,
       te.entry_name,
       te.exit_name,
       te.provider,
       te.external_ref,
       te.receipt_fingerprint,
       te.source_kind,
       te.source_summary,
       te.status,
       te.created_at,
       te.updated_at,
       COALESCE(
         ARRAY(
           SELECT rjd.drive_id
           FROM teslamate_cost_mcp.road_journey_drives rjd
           WHERE rjd.journey_id = te.journey_id
           ORDER BY rjd.sequence_no
         ),
         ARRAY[]::integer[]
       ) AS drive_ids
FROM teslamate_cost_mcp.toll_expenses te;
ALTER VIEW teslamate_cost_mcp.toll_expense_current OWNER TO teslamate;

CREATE OR REPLACE VIEW teslamate_cost_mcp.toll_expense_history AS
SELECT tea.id AS audit_id,
       tea.request_id,
       tea.expense_id,
       tea.actor,
       tea.operation,
       tea.previous_state,
       tea.new_state,
       tea.created_at
FROM teslamate_cost_mcp.toll_expense_audit tea;
ALTER VIEW teslamate_cost_mcp.toll_expense_history OWNER TO teslamate;

CREATE OR REPLACE VIEW teslamate_cost_mcp.road_journey_summary AS
SELECT rj.id AS journey_id,
       rj.car_id,
       rj.start_date,
       rj.end_date,
       rj.start_label,
       rj.end_label,
       rj.match_confidence,
       (
         SELECT count(*)::integer
         FROM teslamate_cost_mcp.road_journey_drives rjd
         WHERE rjd.journey_id = rj.id
       ) AS drive_count,
       COALESCE((
         SELECT sum(d.distance)
         FROM teslamate_cost_mcp.road_journey_drives rjd
         JOIN public.drives d ON d.id = rjd.drive_id
         WHERE rjd.journey_id = rj.id
       ), 0) AS distance_km,
       (
         SELECT count(*)::integer
         FROM teslamate_cost_mcp.toll_expenses te
         WHERE te.journey_id = rj.id AND te.status = 'matched'
       ) AS toll_count,
       COALESCE((
         SELECT sum(te.amount)
         FROM teslamate_cost_mcp.toll_expenses te
         WHERE te.journey_id = rj.id AND te.status = 'matched'
       ), 0) AS toll_total
FROM teslamate_cost_mcp.road_journeys rj
WHERE EXISTS (
  SELECT 1 FROM teslamate_cost_mcp.road_journey_drives rjd
  WHERE rjd.journey_id = rj.id
);
ALTER VIEW teslamate_cost_mcp.road_journey_summary OWNER TO teslamate;

CREATE OR REPLACE FUNCTION teslamate_cost_mcp.apply_cost_change(
  p_request_id uuid,
  p_actor text,
  p_session_id integer,
  p_expected_cost numeric,
  p_new_cost numeric,
  p_source_kind text,
  p_source_summary text
)
RETURNS TABLE (
  audit_id bigint,
  session_id integer,
  previous_cost numeric,
  new_cost numeric,
  applied_at timestamptz,
  idempotent boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, teslamate_cost_mcp
AS $function$
DECLARE
  existing teslamate_cost_mcp.cost_audit%ROWTYPE;
  current_row public.charging_processes%ROWTYPE;
  inserted teslamate_cost_mcp.cost_audit%ROWTYPE;
BEGIN
  IF p_actor NOT IN ('huunter', 'guoguo') THEN
    RAISE EXCEPTION 'unauthorized actor';
  END IF;
  IF p_source_kind NOT IN ('text', 'screenshot') THEN
    RAISE EXCEPTION 'invalid source kind';
  END IF;
  IF p_new_cost IS NOT NULL AND (p_new_cost < 0 OR p_new_cost > 9999.99) THEN
    RAISE EXCEPTION 'cost must be between 0.00 and 9999.99';
  END IF;
  IF length(COALESCE(p_source_summary, '')) > 500 THEN
    RAISE EXCEPTION 'source summary is too long';
  END IF;

  SELECT * INTO existing
  FROM teslamate_cost_mcp.cost_audit
  WHERE request_id = p_request_id;

  IF FOUND THEN
    IF existing.actor IS DISTINCT FROM p_actor
       OR existing.charging_process_id IS DISTINCT FROM p_session_id
       OR existing.new_cost IS DISTINCT FROM p_new_cost THEN
      RAISE EXCEPTION 'request id was already used for a different change';
    END IF;
    RETURN QUERY SELECT existing.id,
                        existing.charging_process_id,
                        existing.previous_cost,
                        existing.new_cost,
                        existing.created_at,
                        true;
    RETURN;
  END IF;

  SELECT * INTO current_row
  FROM public.charging_processes
  WHERE id = p_session_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'unknown charging session: %', p_session_id;
  END IF;
  IF current_row.end_date IS NULL THEN
    RAISE EXCEPTION 'charging session is not complete';
  END IF;
  IF current_row.cost IS DISTINCT FROM p_expected_cost THEN
    RAISE EXCEPTION 'cost conflict: expected %, current %', p_expected_cost, current_row.cost;
  END IF;

  UPDATE public.charging_processes
  SET cost = p_new_cost
  WHERE id = p_session_id;

  INSERT INTO teslamate_cost_mcp.cost_audit (
    request_id,
    actor,
    charging_process_id,
    previous_cost,
    new_cost,
    source_kind,
    source_summary
  )
  VALUES (
    p_request_id,
    p_actor,
    p_session_id,
    current_row.cost,
    p_new_cost,
    p_source_kind,
    COALESCE(p_source_summary, '')
  )
  RETURNING * INTO inserted;

  RETURN QUERY SELECT inserted.id,
                      inserted.charging_process_id,
                      inserted.previous_cost,
                      inserted.new_cost,
                      inserted.created_at,
                      false;
END
$function$;
ALTER FUNCTION teslamate_cost_mcp.apply_cost_change(
  uuid, text, integer, numeric, numeric, text, text
) OWNER TO teslamate;

CREATE OR REPLACE FUNCTION teslamate_cost_mcp.apply_toll_expense_change(
  p_request_id uuid,
  p_actor text,
  p_operation text,
  p_expense_id uuid,
  p_expected_revision integer,
  p_amount numeric,
  p_occurred_at timestamp without time zone,
  p_entry_name text,
  p_exit_name text,
  p_provider text,
  p_external_ref text,
  p_receipt_fingerprint text,
  p_source_kind text,
  p_source_summary text,
  p_journey_id uuid,
  p_drive_ids integer[]
)
RETURNS TABLE (
  expense_id uuid,
  revision integer,
  status text,
  journey_id uuid,
  amount numeric,
  occurred_at timestamp without time zone,
  idempotent boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, teslamate_cost_mcp
AS $function$
DECLARE
  prior_audit teslamate_cost_mcp.toll_expense_audit%ROWTYPE;
  current_expense teslamate_cost_mcp.toll_expenses%ROWTYPE;
  saved_expense teslamate_cost_mcp.toll_expenses%ROWTYPE;
  previous_json jsonb;
  next_json jsonb;
  normalized_drive_ids integer[] := COALESCE(p_drive_ids, ARRAY[]::integer[]);
  drive_count integer;
  min_car_id integer;
  max_car_id integer;
  journey_start timestamp without time zone;
  journey_end timestamp without time zone;
  journey_start_label text;
  journey_end_label text;
  selected_journey_id uuid;
  signature text;
BEGIN
  IF p_actor NOT IN ('huunter', 'guoguo') THEN
    RAISE EXCEPTION 'unauthorized actor';
  END IF;
  IF p_operation NOT IN ('upsert', 'void') THEN
    RAISE EXCEPTION 'invalid toll operation';
  END IF;
  IF p_expense_id IS NULL THEN
    RAISE EXCEPTION 'expense id is required';
  END IF;

  SELECT * INTO prior_audit
  FROM teslamate_cost_mcp.toll_expense_audit
  WHERE request_id = p_request_id;
  IF FOUND THEN
    SELECT * INTO saved_expense
    FROM teslamate_cost_mcp.toll_expenses
    WHERE id = prior_audit.expense_id;
    RETURN QUERY SELECT saved_expense.id, saved_expense.revision,
                        saved_expense.status, saved_expense.journey_id,
                        saved_expense.amount, saved_expense.occurred_at, true;
    RETURN;
  END IF;

  SELECT * INTO current_expense
  FROM teslamate_cost_mcp.toll_expenses
  WHERE id = p_expense_id
  FOR UPDATE;

  IF FOUND THEN
    IF current_expense.actor IS DISTINCT FROM p_actor THEN
      RAISE EXCEPTION 'toll expense belongs to a different actor';
    END IF;
    IF p_expected_revision IS NULL OR current_expense.revision <> p_expected_revision THEN
      RAISE EXCEPTION 'toll expense conflict: expected revision %, current %',
        p_expected_revision, current_expense.revision;
    END IF;
    previous_json := to_jsonb(current_expense);
  ELSIF p_operation = 'void' THEN
    RAISE EXCEPTION 'unknown toll expense: %', p_expense_id;
  ELSIF p_expected_revision IS NOT NULL THEN
    RAISE EXCEPTION 'cannot set expected_revision for a new toll expense';
  END IF;

  IF p_operation = 'void' THEN
    UPDATE teslamate_cost_mcp.toll_expenses AS te
    SET status = 'void',
        revision = te.revision + 1,
        updated_at = now()
    WHERE te.id = p_expense_id
    RETURNING * INTO saved_expense;
  ELSE
    IF p_amount IS NULL OR p_amount < 0 OR p_amount > 9999.99 THEN
      RAISE EXCEPTION 'toll amount must be between 0.00 and 9999.99';
    END IF;
    IF p_occurred_at IS NULL THEN
      RAISE EXCEPTION 'toll occurred_at is required';
    END IF;
    IF p_provider NOT IN ('manual', 'etc', 'wechat', 'alipay', 'other') THEN
      RAISE EXCEPTION 'invalid toll provider';
    END IF;
    IF p_source_kind NOT IN ('text', 'screenshot') THEN
      RAISE EXCEPTION 'invalid source kind';
    END IF;
    IF length(COALESCE(p_entry_name, '')) > 120
       OR length(COALESCE(p_exit_name, '')) > 120
       OR length(COALESCE(p_external_ref, '')) > 120
       OR length(COALESCE(p_source_summary, '')) > 500 THEN
      RAISE EXCEPTION 'toll text field is too long';
    END IF;
    IF p_receipt_fingerprint !~ '^[0-9a-f]{64}$' THEN
      RAISE EXCEPTION 'invalid receipt fingerprint';
    END IF;
    IF cardinality(normalized_drive_ids) > 20 THEN
      RAISE EXCEPTION 'too many drive ids';
    END IF;
    IF cardinality(normalized_drive_ids) <> (
      SELECT count(DISTINCT value) FROM unnest(normalized_drive_ids) AS value
    ) THEN
      RAISE EXCEPTION 'drive ids must not contain duplicates';
    END IF;

    selected_journey_id := NULL;
    IF cardinality(normalized_drive_ids) > 0 THEN
      SELECT count(*), min(car_id), max(car_id), min(start_date), max(end_date)
      INTO drive_count, min_car_id, max_car_id, journey_start, journey_end
      FROM teslamate_cost_mcp.toll_candidate_drives
      WHERE id = ANY(normalized_drive_ids) AND end_date IS NOT NULL;
      IF drive_count <> cardinality(normalized_drive_ids) THEN
        RAISE EXCEPTION 'one or more drives are missing or incomplete';
      END IF;
      IF min_car_id IS DISTINCT FROM max_car_id THEN
        RAISE EXCEPTION 'all drives must belong to one vehicle';
      END IF;
      SELECT COALESCE(start_address, '') INTO journey_start_label
      FROM teslamate_cost_mcp.toll_candidate_drives
      WHERE id = normalized_drive_ids[1];
      SELECT COALESCE(end_address, '') INTO journey_end_label
      FROM teslamate_cost_mcp.toll_candidate_drives
      WHERE id = normalized_drive_ids[cardinality(normalized_drive_ids)];
      signature := md5(array_to_string(normalized_drive_ids, ','));
      INSERT INTO teslamate_cost_mcp.road_journeys (
        id, car_id, drive_signature, start_date, end_date,
        start_label, end_label, updated_at
      ) VALUES (
        p_journey_id, min_car_id, signature, journey_start, journey_end,
        COALESCE(journey_start_label, ''), COALESCE(journey_end_label, ''), now()
      )
      ON CONFLICT (drive_signature) DO UPDATE SET
        start_date = EXCLUDED.start_date,
        end_date = EXCLUDED.end_date,
        start_label = EXCLUDED.start_label,
        end_label = EXCLUDED.end_label,
        updated_at = now()
      RETURNING id INTO selected_journey_id;

      DELETE FROM teslamate_cost_mcp.road_journey_drives AS rjd
      WHERE rjd.journey_id = selected_journey_id;
      INSERT INTO teslamate_cost_mcp.road_journey_drives (
        journey_id, drive_id, sequence_no
      )
      SELECT selected_journey_id, value, ordinal::smallint
      FROM unnest(normalized_drive_ids) WITH ORDINALITY AS drives(value, ordinal);
    END IF;

    IF current_expense.id IS NULL THEN
      INSERT INTO teslamate_cost_mcp.toll_expenses (
        id, actor, journey_id, amount, occurred_at, entry_name, exit_name,
        provider, external_ref, receipt_fingerprint, source_kind,
        source_summary, status
      ) VALUES (
        p_expense_id, p_actor, selected_journey_id, p_amount, p_occurred_at,
        COALESCE(p_entry_name, ''), COALESCE(p_exit_name, ''), p_provider,
        COALESCE(p_external_ref, ''), p_receipt_fingerprint, p_source_kind,
        COALESCE(p_source_summary, ''),
        CASE WHEN selected_journey_id IS NULL THEN 'pending_match' ELSE 'matched' END
      )
      RETURNING * INTO saved_expense;
    ELSE
      UPDATE teslamate_cost_mcp.toll_expenses AS te
      SET journey_id = selected_journey_id,
          revision = te.revision + 1,
          amount = p_amount,
          occurred_at = p_occurred_at,
          entry_name = COALESCE(p_entry_name, ''),
          exit_name = COALESCE(p_exit_name, ''),
          provider = p_provider,
          external_ref = COALESCE(p_external_ref, ''),
          receipt_fingerprint = p_receipt_fingerprint,
          source_kind = p_source_kind,
          source_summary = COALESCE(p_source_summary, ''),
          status = CASE WHEN selected_journey_id IS NULL THEN 'pending_match' ELSE 'matched' END,
          updated_at = now()
      WHERE te.id = p_expense_id
      RETURNING * INTO saved_expense;
    END IF;
  END IF;

  next_json := to_jsonb(saved_expense);
  INSERT INTO teslamate_cost_mcp.toll_expense_audit (
    request_id, expense_id, actor, operation, previous_state, new_state
  ) VALUES (
    p_request_id, saved_expense.id, p_actor, p_operation, previous_json, next_json
  );

  RETURN QUERY SELECT saved_expense.id, saved_expense.revision,
                      saved_expense.status, saved_expense.journey_id,
                      saved_expense.amount, saved_expense.occurred_at, false;
END
$function$;
ALTER FUNCTION teslamate_cost_mcp.apply_toll_expense_change(
  uuid, text, text, uuid, integer, numeric, timestamp without time zone,
  text, text, text, text, text, text, text, uuid, integer[]
) OWNER TO teslamate;

REVOKE ALL ON SCHEMA public FROM teslamate_cost_mcp;
REVOKE ALL ON SCHEMA teslamate_cost_mcp FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA teslamate_cost_mcp FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA teslamate_cost_mcp FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA teslamate_cost_mcp FROM teslamate_cost_mcp;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA teslamate_cost_mcp FROM teslamate_cost_mcp;

GRANT USAGE ON SCHEMA teslamate_cost_mcp TO teslamate_cost_mcp;
GRANT SELECT ON teslamate_cost_mcp.charging_sessions TO teslamate_cost_mcp;
GRANT SELECT ON teslamate_cost_mcp.cost_history TO teslamate_cost_mcp;
GRANT SELECT ON teslamate_cost_mcp.toll_candidate_drives TO teslamate_cost_mcp;
GRANT SELECT ON teslamate_cost_mcp.toll_expense_current TO teslamate_cost_mcp;
GRANT SELECT ON teslamate_cost_mcp.toll_expense_history TO teslamate_cost_mcp;
GRANT SELECT ON teslamate_cost_mcp.road_journey_summary TO teslamate_cost_mcp;
GRANT EXECUTE ON FUNCTION teslamate_cost_mcp.apply_cost_change(
  uuid, text, integer, numeric, numeric, text, text
) TO teslamate_cost_mcp;
GRANT EXECUTE ON FUNCTION teslamate_cost_mcp.apply_toll_expense_change(
  uuid, text, text, uuid, integer, numeric, timestamp without time zone,
  text, text, text, text, text, text, text, uuid, integer[]
) TO teslamate_cost_mcp;
